[package]
name = "processhollowing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser",
"memoryapi","libloaderapi",
"processthreadsapi","synchapi","errhandlingapi"] }
widestring = "1.0.2"
ntapi = "0.4.0"